load("@bazel_skylib//rules:build_test.bzl", "build_test")

build_test(
    name = "tests",
    targets = [
        "//src/main/java/com/fillmore_labs/kafka/sensors/app",
        "//src/main/java/com/fillmore_labs/kafka/sensors/app:kafka_sensors",
    ],
)
