---
steps:
  - label: ':bazel: Test'
    commands:
      - bazel test //src/test/...

  - wait

  - label: ':docker: Upload Docker image'
    commands:
      - bazel run //src/main/java/com/fillmore_labs/kafka/sensors/benchmark:push_benchmark
    branches: "main"
