---
steps:
  - label: ':bazel: Test'
    commands:
      - bazel test --config=ci //...

  - wait

  - label: ':docker: Upload Docker images'
    commands:
      - bazel run --config=ci --stamp
        //src/main/java/com/fillmore_labs/kafka/sensors/benchmark:push_benchmark_amd64
      - bazel run --config=ci --stamp
        //src/main/java/com/fillmore_labs/kafka/sensors/benchmark:push_benchmark_arm64
      - crane index append --docker-empty-base
        --manifest fillmorelabs/serialization-benchmark:latest-amd64
        --manifest fillmorelabs/serialization-benchmark:latest-arm64
        --tag fillmorelabs/serialization-benchmark:latest
    branches: "main"
