---
steps:
  - label: ':bazel: Build & Test'
    commands:
      - bazel build --config=ci //src/main/...
      - bazel test --config=ci //src/test/...
    branches: "!main"

  - label: ':codecov: + :codeclimate: Test & Coverage'
    commands:
      - bazel coverage --config=ci //src/test/...
      - sh .buildkite/upload_coverage.sh
    branches: "main"
