---
steps:
  - label: ':bazel: Build & Test'
    commands:
      - bazel build --config=ci //src/...
      - bazel test --config=ci //...
    branches: "!main"

  - label: ':codecov: + :codeclimate: Test & Coverage'
    commands:
      - bazel coverage --config=ci //src/test/...
      - sh .buildkite/upload_coverage.sh "$(bazel info output_path)/_coverage/_coverage_report.dat"
    plugins:
      - test-collector#v1.10.1:
          base-path: "$BAZEL_TESTLOGS"
          files: "*/test.xml"
          format: "junit"
    branches: "main"
