---
steps:
  - label: ':bazel: Test & Coverage'
    commands:
      - bazel coverage //src/test/...
    branches: "main"
  - wait
  - label: ':codecov: Upload Coverage'
    commands:
      - codecov -s "$(bazel info bazel-testlogs)"
    branches: "main"
