---
steps:
  - label: ':bazel: Test & Coverage'
    commands:
      - bazel coverage --combined_report=lcov //src/test/...
  - wait
  - label: ':codecov: Upload Coverage'
    commands:
      - codecov -f "$(bazel info output_path)/_coverage/_coverage_report.dat"
    branches: "main"
