---
steps:
  - label: ':bazel: Build'
    commands:
      - bazel build --config=ci //src/...

  - wait

  - label: ':bazel: Test'
    commands:
      - bazel test --config=ci //:lint_check //src/test/...
