package(default_visibility = ["//visibility:public"])

filegroup(
    name = "conf",
    srcs = ["application.yaml"],
)

filegroup(
    name = "logging",
    srcs = ["logging.properties"],
)

filegroup(
    name = "shortlog",
    srcs = ["shortlog.properties"],
)
