package(default_visibility = ["//src/test:__subpackages__"])

filegroup(
    name = "output_schema",
    srcs = ["output-schema.json"],
)

filegroup(
    name = "input_samples",
    srcs = ["input-samples.jsonl"],
)
